version: '3.8'

services:
  local-proxy:
    image: ghcr.io/tarampampam/3proxy:1
    container_name: local-proxy
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PROXY_PORT: 3128
      LOG_OUTPUT: /dev/stdout
      EXTRA_CONFIG: |
        parent 1000 http ${PROXY_HOST} ${PROXY_PORT} ${PROXY_USER} ${PROXY_PASSWORD}
    networks:
      - bot-network

  telegram-bot:
    build: .
    container_name: telegram-calendar-bot
    restart: unless-stopped
    depends_on:
      - local-proxy
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - TZ=Europe/Moscow
      - JAVA_TOOL_OPTIONS=-Djava.net.useSystemProxies=true -DproxySet=true -Dhttp.proxyHost=local-proxy -Dhttp.proxyPort=8888 -Dhttps.proxyHost=local-proxy -Dhttps.proxyPort=8888 -Dhttp.nonProxyHosts=localhost|127.0.0.1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge