version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram-calendar-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # Оставляем только логи если нужно
      - ./logs:/app/logs
    environment:
      - SPRING_PROFILES_ACTIVE=production
    # Если нужен веб-интерфейс
    # ports:
    #   - "8080:8080"
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge