version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram-calendar-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - TZ=Europe/Moscow
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge